spring:
  datasource:
    url: jdbc:mysql://localhost:3306/greenroots?useSSL=false&allowPublicKeyRetrieval=true
    username: greenroots_user
    password: greenroots_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration/mysql